In [4]:
import cv2
import numpy as np

In [5]:
img = cv2.imread('Eagle.jpg',0)

In [6]:
cv2.imshow('Eagle',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Negative of an Image

#### Inbuilt bitwise

In [7]:
img_inverted = cv2.bitwise_not(img)
cv2.imshow('Inverted Eagle',img_inverted)
cv2.imshow('Eagle',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[11 11 11 ... 11 11 11]
 [11 11 11 ... 11 11 11]
 [11 11 11 ... 11 11 11]
 ...
 [11 11 11 ... 12 12 12]
 [11 11 11 ... 11 11 11]
 [11 11 11 ... 11 11 11]]


In [9]:
img_inverted2 = 255 -img
cv2.imshow('',img_inverted2)
cv2.waitKey(0)
cv2.destroyAllWindows()